{
 "title": "Alarm list",
 "tags": [
  "k8s",
  "art-dashboards"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 22, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Statefulsets",
   "type": "table",
   "gridPos": { "h": 22, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Daemonset",
   "type": "table",
   "gridPos": { "h": 22, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_available",
     "legendFormat": "{{daemonset}}"
    }
   ]
  }
 ]
}