{
 "title": "k8s pod",
 "tags": [
  "k8s",
  "art-dashboards"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",resource=\"memory\"}",
     "legendFormat": "Limit: {{container}}"
    },
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"\",container=~\"$container\",container!=\"POD\",pod=~\"$pod\"})",
     "legendFormat": "Current: {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",resource=\"memory\"}",
     "legendFormat": "Request: {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",resource=\"cpu\"}",
     "legendFormat": "Limit: {{container}}"
    },
    {
     "expr": "sum by(container) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container!=\"\",container=~\"$container\",container!=\"POD\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "Current: {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",resource=\"cpu\"}",
     "legendFormat": "Reuest: {{container}}"
    }
   ]
  },
  {
   "title": "CPU throttled",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\",container=~\"$container\",pod=~\"$pod\"}\n/container_cpu_cfs_periods_total{namespace=\"$namespace\",container=~\"$container\",pod=\"$pod\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}