### 04-http-https-route.yaml
GET http://testapp.kryukov.local

###  05-path-redirect.yaml
GET https://testapp.kryukov.local/auth
###
GET https://testapp.kryukov.local/login

### 06-rewrite.yaml
GET https://testapp.kryukov.local/login/22/12

### 07-header-modifiers.yaml
GET https://testapp.kryukov.local/

### 08-canary.yaml
### Old app
GET https://testapp.kryukov.local/

### New app
GET https://testapp.kryukov.local/
app-version: new

### 09-blue-green.yaml
### Повторять запрос минимум 10-ть раз.
GET https://testapp.kryukov.local/